version: "3.8"

services:
  memora-web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html/sistemas/memora-env
    environment:
      - DJANGO_SETTINGS_MODULE=memora.settings

volumes:
  memora_data:
